### ISSUE TITLE
MailWatch report not showing quarantine emails.

### ISSUE THREAD

**Issue by Lungape** [mailwatch/1.2.0#1176]
Hi,
I just installed the postfix+mailscanner+mailwatch, everything is running fine with the setup, my only problem is when i run mailwatch_quarantine_report.php i receive the message (PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /usr/local/www/apache24/data/functions.php on line 1115 ) with a reply of ( ==== Found 0 quarantined e-mails).

But when I go to the interface web there a lot of messages on the quarantine folder.

Please, thanks for any help.

![Screen Shot 2020-04-25 at 14 30 41](https://user-images.githubusercontent.com/64315842/80281221-9acc0380-8701-11ea-97b3-c8ec98a115b0.jpg)
![Screen Shot 2020-04-25 at 14 33 07](https://user-images.githubusercontent.com/64315842/80281245-c0590d00-8701-11ea-95d6-4c1eafb004a9.jpg)
![Screen Shot 2020-04-25 at 14 33 07](https://user-images.githubusercontent.com/64315842/80281253-cc44cf00-8701-11ea-96e3-f460b2b75681.jpg)
![Screen Shot 2020-04-25 at 14 33 13](https://user-images.githubusercontent.com/64315842/80281254-ce0e9280-8701-11ea-90c9-13c6b257e8bc.jpg)

**Comment by ghost** [comment]
Do you have users defined in MailWatch?

**Comment by Lungape** [comment]
yes, with the send email enable.



![Screen Shot 2020-04-25 at 14 49 14](https://user-images.githubusercontent.com/64315842/80281571-03b47b00-8704-11ea-9441-1992040d91dd.jpg)

**Comment by ghost** [comment]
Are the user names in the form of an email address?

**Comment by Lungape** [comment]
No, but I changed the report recipient with the email that needs to receive the report.



![Screen Shot 2020-04-25 at 14 48 30](https://user-images.githubusercontent.com/64315842/80282352-df0ed200-8708-11ea-98de-db61f6f1a5d2.jpg)

**Comment by ghost** [comment]
Did administrator actually receive any emails?  (The report is per user)

**Comment by Lungape** [comment]
I did a test changing the username (admin) for the email following your previous message and the administrator received the email with one spam.

but, I thought that the administrator will receive all spam on the quarantine. But this is not the case, right?

There is any kind of email report that the administrator receives all the spams so he can access the interface and check/release ?

**Comment by Lungape** [comment]
if I understood you correctly the report is per user based?
If this is the case, this is a problem in my setup, because I am using as an SMTP gateway and not as email server, there is no user on the postfix itself.

**Comment by Skywalker-11** [comment]
Please check out the file [quarantine_report.inc.php](https://github.com/mailwatch/MailWatch/blob/fix1176/mailscanner/quarantine_report.inc.php) from that PR. It should fix the issue.

**Comment by Lungape** [comment]
Hi Guys,
I download and replaced the quarantine_report.inc.php, but i still getting the same issue.
Just to make clear, i am receiving the email when i changed the username admin to the email address administrator@XXXXX, as explained early and doing this I received an email with only the admin user spam message.
But not for spams on the quarantine folder as an admin report for all users.


My question is the there is a report to the global admin with all spams?
and the message (Deprecated: Function get_magic_quotes_gpc()) is it normal ?


![Screen Shot 2020-04-25 at 20 27 04](https://user-images.githubusercontent.com/64315842/80289035-d8498480-8733-11ea-81de-9a2802e84821.jpg)

![Screen Shot 2020-04-25 at 20 32 59](https://user-images.githubusercontent.com/64315842/80289059-029b4200-8734-11ea-904a-94af2316bb25.jpg)

**Comment by Skywalker-11** [comment]
I updated the PR can you check again?

The warning `Deprecated: Function get_magic_quotes_gpc()` is normal for PHP >=7.4.0 and can safely be ignored. For older PHP versions <5.4.0 there is a feature `magic_quotes` which requires special handling to prevent issues. With PHP >=5.4.0  that feature doesn't exist anymore. If MailWatch stops supporting PHP <5.4.0 we will remove that function.

**Comment by Lungape** [comment]
Hi Guys,
Thank you very much, it's working now.


![Screen Shot 2020-04-26 at 09 24 56](https://user-images.githubusercontent.com/64315842/80302145-30b66b80-87a0-11ea-8f8b-de700d2c7519.jpg)

**Comment by endelwar** [comment]
> If MailWatch stops supporting PHP <5.4.0 we will remove that function.

MailWatch officially supports PHP from 5.4 to 7, unofficially 5.3 is still supported with some limitation.
